# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise32"

  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.network :forwarded_port, guest: 8000, host: 8080

  config.vm.synced_folder "../", "/vagrant", id: "vagrant-root"
  
  config.vm.provision :shell, :inline => "aptitude -q2 update"
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet"
    puppet.module_path = "puppet/modules"
  	puppet.manifest_file  = "base.pp"
  end

end
